apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - http:
      paths:
      - backend:
          serviceName: {{ template "fullname" $ }}
          servicePort: {{ $.Values.service.externalPort }}
        path: /
    host: {{ . | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  - secretName: {{ .Values.ingress.tls.secretName }}
    hosts:
{{ toYaml .Values.ingress.hosts | indent 4 }}
{{- end -}}
