sudo: required

language: generic

services:
  - docker

before_install:
 - curl https://storage.googleapis.com/kubernetes-release/release/v1.2.4/bin/linux/amd64/kubectl > /tmp/kubectl && chmod +x /tmp/kubectl
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker build -t prydonius/node-todo:$TRAVIS_BUILD_NUMBER .
 - docker push prydonius/node-todo:$TRAVIS_BUILD_NUMBER

script:
  - /tmp/kubectl --insecure-skip-tls-verify --server "$KUBE_SERVER" --username "$KUBE_USERNAME" --password="$KUBE_PASSWORD" --namespace helm rolling-update node-todo --image prydonius/node-todo:$TRAVIS_BUILD_NUMBER
