# helm install stable/jenkins -f ./overrides.yaml

Master:
  # exposed via ingress
  ServiceType: ClusterIP
  HostName: jenkins.prydoni.us
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
    TLS:
      - secretName: jenkins.prydoni.us-tls
        hosts:
          - jenkins.prydoni.us
